### ISSUE TITLE
no listeners executed but present with rbac module

### ISSUE THREAD

**Issue by bartwalczak1** [silverbp/hubot-stackstorm-auth#1]
Hi there,

I think this might not be related and is simply misconfiguration, but since I've used this repo to add some authorization between user and st2, I thought someone smarter might point me in the right direction. 

So I've used this package instead of hubot-stackstorm, added hubot-rbac, set up action alias in st2 like so:
```
---
name: "ec2_describe"
pack: "aws"
action_ref: "aws.ec2_get_all_instances"
description: "describe ec2 instance"
formats:
  - "describe ec2"
  - "ec2 describe ec2"
ack:
  format: "Roger! Collecting data..."
extra:
  hubot_auth:
    roles:
      - devops
result:
  format: |
    {% for line in execution.result.result %}
       {% for ec2 in line -%}
         {{ ec2.id }} - {{ ec2.state }} - {{ ec2.tags.Name }} - {{ ec2.ip_address }} - {{ ec2.private_ip_address }}
       {% endfor %}
    {% endfor %}
```
When executing `describe ec2` nothing happens. In logs I see:
```
[Tue Aug 08 2017 15:16:03 GMT+0000 (UTC)] DEBUG No listeners executed; falling back to catch-all
```
Also I was playing around with hubot rbac policies and from the log I can see as follows:
```
[Tue Aug 08 2017 15:15:48 GMT+0000 (UTC)] DEBUG hubot-rbac: policies -> Map { "devops": Set { "st2.ec2_check_state" } }
[Tue Aug 08 2017 15:15:48 GMT+0000 (UTC)] DEBUG hubot-rbac: subjects -> Map { "bwalczak": Set { "st2.ec2_describe", "devops" } }
[Tue Aug 08 2017 15:15:48 GMT+0000 (UTC)] DEBUG hubot-rbac: default -> devops
```
I am at the point that I don't know what else is missing?
